"""rename_unit_for_fdw

Revision ID: c7f7f87631b8
Revises: 1dfa903d673e
Create Date: 2024-11-19 18:37:01.830106

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c7f7f87631b8"
down_revision = "1dfa903d673e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servicecunit",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_servicecunit_name"), "servicecunit", ["name"], unique=False
    )
    op.drop_index("ix_unit_name", table_name="unit")
    op.drop_table("unit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="unit_pkey"),
    )
    op.create_index("ix_unit_name", "unit", ["name"], unique=False)
    op.drop_index(op.f("ix_servicecunit_name"), table_name="servicecunit")
    op.drop_table("servicecunit")
    # ### end Alembic commands ###
